### ISSUE TITLE
ohne pr0 möglich?

### ISSUE THREAD

**Issue by capsload2** [clusterzx/pr0lator#1]
Hallo,

gibt es eine Mǒglichkeit das ganze ohne pr0gramm Account zu nutzen?

**Comment by clusterzx** [comment]
> Hallo,
> 
> 
> 
> gibt es eine Mǒglichkeit das ganze ohne pr0gramm Account zu nutzen?

Hey,

Ja das wäre möglich. Wenn du es selber hostest kannst du dir die convert.py umschreiben in wenigen Steps. 

Ich werde bald einen großen Commit mit neuer Version pushen wo man auch ohne Account Dateien hochladen kann. 

VG
